import { CATEGORY_RULES } from "@/constants/categories.constant";
import { BASE_INSTRUCTIONS } from "@/lib/prompts/tips/instructions.prompt";
import { Category } from "@/types/category";

const USER_MESSAGES: Record<Category, string> = {
  [Category.GIT_COMMAND]: "Give me a Git tip",
  [Category.TERMINAL]: "Give me a terminal/shell tip",
  [Category.EDITOR]: "Give me a code editor tip",
  [Category.REACT]: "Give me a React tip",
  [Category.CSS]: "Give me a CSS tip",
  [Category.TYPESCRIPT]: "Give me a TypeScript tip",
  [Category.JAVASCRIPT]: "Give me a JavaScript tip",
  [Category.DOCKER]: "Give me a Docker tip",
  [Category.DEVTOOLS]: "Give me a browser DevTools tip",
  [Category.SQL]: "Give me a SQL tip",
};

const CATEGORY_TOPICS: Record<Category, string[]> = {
  [Category.GIT_COMMAND]: [
    "undoing changes safely",
    "interactive rebase",
    "stashing and stash management",
    "cherry-picking commits",
    "git bisect for bug hunting",
    "reflog and recovering lost commits",
    "aliases and shortcuts",
    "advanced log formatting",
    "submodules",
    "worktrees",
    "sparse checkout",
    "partial clones and shallow clones",
    "signing commits",
    "git hooks",
    "branch cleanup strategies",
  ],
  [Category.TERMINAL]: [
    "file searching with find or fd",
    "text processing with awk or sed",
    "process management and signals",
    "job control and background tasks",
    "shell aliases and functions",
    "pipes and redirection tricks",
    "history search and navigation",
    "terminal multiplexer tips (tmux or screen)",
    "file permissions and chmod",
    "environment variables and export",
    "cron jobs and scheduling",
    "network commands (curl, wget, netstat)",
    "disk usage and df/du",
    "stream editing and xargs",
    "brace expansion and globbing",
  ],
  [Category.EDITOR]: [
    "multi-cursor editing",
    "command palette productivity",
    "code folding and navigation",
    "integrated terminal tricks",
    "snippet creation and expansion",
    "refactoring shortcuts",
    "file and symbol search",
    "split editor and layouts",
    "git integration shortcuts",
    "debugging inside the editor",
    "task runner configuration",
    "workspace settings vs user settings",
    "keyboard shortcut customization",
    "extensions for productivity",
    "Vim mode or Vim keybindings",
  ],
  [Category.REACT]: [
    "useCallback and memoization",
    "useMemo for expensive calculations",
    "useRef for DOM access and mutable values",
    "custom hooks patterns",
    "useReducer for complex state",
    "Context API best practices",
    "lazy loading and code splitting",
    "React.memo and preventing re-renders",
    "error boundaries",
    "suspense and concurrent features",
    "compound component pattern",
    "render props pattern",
    "controlled vs uncontrolled components",
    "key prop and list reconciliation",
    "useEffect cleanup and dependencies",
  ],
  [Category.CSS]: [
    "CSS Grid advanced placement",
    "Flexbox alignment tricks",
    "custom properties (CSS variables)",
    "container queries",
    "the :has() selector",
    "CSS animations and keyframes",
    "clip-path and masking",
    "CSS logical properties",
    "scroll-driven animations",
    "CSS nesting",
    "aspect-ratio property",
    "subgrid",
    "color-mix() and oklch colors",
    "CSS layers (@layer)",
    "view transitions API",
  ],
  [Category.TYPESCRIPT]: [
    "template literal types",
    "conditional types and the infer keyword",
    "mapped types and key remapping with as",
    "discriminated unions",
    "type narrowing and type guards",
    "the satisfies operator",
    "branded and nominal types",
    "recursive types",
    "utility types: ReturnType, Parameters, Awaited, InstanceType",
    "utility types: Partial, Required, Pick, Omit, Record",
    "generic constraints and default type parameters",
    "as const and const type parameters",
    "unknown vs any and safe type assertions",
    "function overloads",
    "tuple types and variadic tuples",
    "index signatures and Record patterns",
    "type predicates and assertion functions",
    "declaration merging and module augmentation",
    "intersection types and interface composition",
    "strict mode flags and their benefits",
  ],
  [Category.JAVASCRIPT]: [
    "optional chaining and nullish coalescing",
    "destructuring patterns (arrays and objects)",
    "logical assignment operators (&&=, ||=, ??=)",
    "Array.at() and Array.findLast()",
    "Array.toSorted, toReversed, toSpliced, with",
    "Object.groupBy and Map.groupBy",
    "structuredClone for deep copying",
    "Promise.allSettled and Promise.any",
    "AbortController and cancellable fetches",
    "async iterators and for-await-of",
    "WeakRef and FinalizationRegistry",
    "Proxy and Reflect",
    "Symbol and well-known symbols",
    "generator functions",
    "dynamic import() and code splitting",
    "crypto.randomUUID and Web Crypto API",
    "Intl API for formatting",
    "error cause and custom errors",
    "top-level await",
    "tagged template literals",
  ],
  [Category.DOCKER]: [
    "multi-stage builds to reduce image size",
    "layer caching and build order",
    ".dockerignore best practices",
    "health checks in containers",
    "non-root user security",
    "environment variables and secrets",
    "named volumes vs bind mounts",
    "Docker Compose depends_on and healthchecks",
    "Docker Compose profiles",
    "Docker Compose watch mode",
    "BuildKit advanced features",
    "read-only filesystems",
    "resource limits (CPU and memory)",
    "multi-platform builds with buildx",
    "pruning unused images, containers and volumes",
    "docker inspect and debugging containers",
    "override files in Docker Compose",
    "network modes and custom networks",
    "minimal base images (alpine, distroless, scratch)",
  ],
  [Category.DEVTOOLS]: [
    "conditional breakpoints",
    "logpoints as non-breaking breakpoints",
    "console.table for structured data",
    "live expressions in the console",
    "network request blocking",
    "performance flamegraph analysis",
    "heap snapshot for detecting memory leaks",
    "coverage tab to find dead code",
    "command palette shortcuts (Ctrl+Shift+P)",
    "$0, $1, $$ and $x selectors in the console",
    "custom JavaScript snippets",
    "network throttling and offline simulation",
    "forcing element state (:hover, :focus, :active)",
    "event listener inspection on elements",
    "copy as fetch or copy as curl from network panel",
    "watch expressions in Sources panel",
    "console.group, console.time and console.count",
    "local overrides to persist edits across reloads",
    "accessibility tree and audit",
    "CSS overview panel",
  ],
  [Category.SQL]: [
    "window functions: ROW_NUMBER, RANK, DENSE_RANK",
    "window functions: LAG and LEAD for row comparison",
    "CTEs and recursive CTEs",
    "EXPLAIN ANALYZE and query plan reading",
    "index types and when to use them",
    "upsert with INSERT ... ON CONFLICT",
    "RETURNING clause after INSERT, UPDATE, DELETE",
    "keyset pagination vs LIMIT/OFFSET",
    "NULL handling: COALESCE, NULLIF, IS DISTINCT FROM",
    "CASE WHEN for conditional logic",
    "correlated subqueries vs JOINs",
    "EXISTS vs IN for existence checks",
    "GROUP BY with HAVING vs WHERE",
    "transactions and isolation levels",
    "JSONB operations in PostgreSQL",
    "date and time arithmetic",
    "FILTER clause in aggregations",
    "self-joins and hierarchical queries",
    "DISTINCT ON in PostgreSQL",
    "partial indexes for performance",
  ],
};

const pickRandom = <T>(arr: T[]): T =>
  arr[Math.floor(Math.random() * arr.length)];

export const buildPrompt = (category: Category): string => {
  const categoryRules = CATEGORY_RULES[category];

  if (!categoryRules) {
    throw new Error(`Unknown category: ${category}`);
  }

  return `${BASE_INSTRUCTIONS}\n\n${categoryRules}`;
};

export const buildUserMessage = (category: Category): string => {
  const topic = pickRandom(CATEGORY_TOPICS[category]);
  return `${USER_MESSAGES[category]}. Topic to cover: ${topic}`;
};

export const isValidCategory = (category: string): category is Category => {
  return Object.values(Category).includes(category as Category);
};
