import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import { Header } from "@/components/layout/header";
import React from "react";

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '600', '700', '800']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
    <body className={'h-full'}>
    <Header/>
    {children}
    </body>
    </html>
  );
}
