"use client";
import { useTips } from "@/hooks/useTips";
import { useToast } from "@/hooks/useToast";
import React, { useEffect } from "react";
import { useTipStore } from "@/stores/Tip.store";
import { CategoryBadge } from "@/components/tips/category-badge";
import { MainContainer } from "@/components/tips/main-container";
import { Category } from "@/types/category";
import { Examples } from "@/components/tips/examples";
import Keno from "@/components/ui/Keno";
import Link from "next/link";

export default function Home() {
  const { getTip } = useTips();
  const toast = useToast();
  const tip = useTipStore((state) => state.tip);
  const showExamples = useTipStore((state) => state.showExamples);

  const examplesCount = tip?.examples?.length ?? 0;

  const handleError = (e: unknown) => {
    const msg = e instanceof Error ? e.message : "";
    if (msg === "RATE_LIMITED") {
      toast.error("Sorry, too many requests. (10 req/min)");
    } else {
      toast.error("Failed to get a tip. Please try again.");
    }
  };

  const handleNewTip = async (type: Category) => {
    try {
      await getTip(type);
    } catch (e) {
      handleError(e);
    }
  };

  useEffect(() => {
    getTip(Category.GIT_COMMAND).catch(handleError);
  }, []);

  return (
    <main className="mt-10 mb-20 flex flex-col items-center justify-center px-4 md:mt-18 md:mb-32 lg:px-0">
      <Keno />

      <div
        className="my-6 flex w-full flex-wrap justify-center gap-2 lg:max-w-4/9"
        data-testid="categories-list"
      >
        {Object.values(Category).map((category: Category) => (
          <CategoryBadge
            onClick={() => handleNewTip(category)}
            key={category}
            type={category}
            data-testid={`filter-badge-${category}`}
          />
        ))}
      </div>

      <MainContainer />

      {showExamples && examplesCount > 0 && <Examples />}

      <div className={"mt-5"}>
        <small data-testid="ai-disclaimer">
          <span className={"me-1"}>
            All content is generated by AI | Powered by
          </span>
          <Link
            className={"underline"}
            target={"_blank"}
            href={"https://platform.openai.com/docs/overview"}
          >
            OpenAI API
          </Link>
        </small>
      </div>
    </main>
  );
}
