"use client";
import Image from "next/image";
import ItsFine from "../assets/images/fine.png";
import { useTips } from "@/hooks/useTips";
import React, { useEffect } from "react";
import { useTipStore } from "@/stores/Tip.store";
import { CategoryBadge } from "@/components/tips/category-badge";
import { MainContainer } from "@/components/tips/main-container";
import { Category } from "@/types/category";
import { Examples } from "@/components/tips/examples";
import Link from "next/link";

export default function Home() {
  const { getTip } = useTips();
  const tip = useTipStore((state) => state.tip);
  const showExamples = useTipStore((state) => state.showExamples);

  const examplesCount = tip?.examples?.length ?? 0;

  const handleNewTip = async (type: Category) => {
    await getTip(type);
  };

  useEffect(() => {
    getTip();
  }, []);

  return (
    <main className="mt-18 mb-32 flex flex-col items-center justify-center">
      <Image src={ItsFine} alt={"It is fine"} width={200} />

      <div className={"my-6 flex gap-2"}>
        {[Category.GIT_COMMAND, Category.TERMINAL, Category.EDITOR].map(
          (category: Category) => (
            <CategoryBadge
              onClick={() => handleNewTip(category)}
              key={category}
              type={category}
            />
          )
        )}
      </div>

      <MainContainer />

      {showExamples && examplesCount > 0 && <Examples />}

      <div className={"mt-5"}>
        <small>
          <span className={"me-1"}>
            All content is generated by AI | Powered by
          </span>
          <Link
            className={"underline"}
            target={"_blank"}
            href={"https://platform.openai.com/docs/overview"}
          >
            OpenAI API
          </Link>
        </small>
      </div>
    </main>
  );
}
